name: Deploy Image Guessing Game

on:
  workflow_dispatch:
    inputs:
      address:
        description: "Contract Address"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: create env file
        run: |
          touch .env
          echo VITE_APP_MORALIS_API_KEY='${{ secrets.VITE_APP_MORALIS_API_KEY }}' >> .env
          echo VITE_APP_NFT_UP_KEY='${{ secrets.VITE_APP_NFT_UP_KEY }}' >> .env

      - name: Write Address to JSON
        run: |
          echo '{"address": "${{ github.event.inputs.address }}"}' > ./src/assets/contract/address.json

      - name: Build application
        run: npm run build
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
